# This is a basic workflow to help you get started with Actions

name: Update Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: Moosync.types
      - name: Clone webpage
        uses: actions/checkout@v3
        with:
          repository: Moosync/Moosync.github.io
          path: Moosync.web
          token: ${{ secrets.WEB_TOKEN }}
          
      - name: Install deps
        run: yarn install

      - name: Copy files and push
        run: |
          yarn docs
          git config --global user.email "actions@github.com"
          git config --global user.name "Docs update"
          rm -rf $GITHUB_WORKSPACE/Moosync.web/docs
          cp -r $GITHUB_WORKSPACE/Moosync.types/docs $GITHUB_WORKSPACE/Moosync.web
          cd $GITHUB_WORKSPACE/Moosync.web
          git add -A
          git diff-index --quiet HEAD -- || git commit -m "sync from Moosync/extension-api-types"
          git push
